### ISSUE TITLE
ScenariStream Operational issues

### ISSUE THREAD

**Issue by KSSW** [cubicibo/ScenariStream#2]
Video: https://youtu.be/sV-4tuXymdU

May I ask the author why I installed the Python library but did not generate PES files when running the program?

**Comment by cubicibo** [comment]
Hi @KSSW 
Your video link does not work.

If you wish to do conversions through the command line. You can simply download the repository, then use:
`python3 client.py -s C:\folderA\input.sup -o C:\folderB\output.pes`

If you want to add your own Python code around ScenariStream, you can use `client.py` code as an example.

**Comment by KSSW** [comment]
Thank you. It has been resolved
But I don't know why importing Scenarist UHD will result in an error
![image](https://github.com/cubicibo/ScenariStream/assets/76238373/7e7dcea2-013d-4605-bc1d-b8d07ca07347)
Perhaps Scenarist UHD detected non-standard PG stream
I feel like can't solve this problem

**Comment by cubicibo** [comment]
Please read, and try Point **#.1** on this comment: https://github.com/cubicibo/ScenariStream/issues/1#issuecomment-1976160440

DGDemux and old versions of tsMuxer must have the SUP file fixed.

if you have generated your SUP file with avs2bdnxml, PunkGraphicStream or other broken tools, it may be non-standard and nothing can save it.

**Comment by KSSW** [comment]
I have read this article carefully
When I install SUPer Python package installations ：
![image](https://github.com/cubicibo/ScenariStream/assets/76238373/dc681341-3389-4514-852f-eff1e409d701)
I can't install it

**Comment by cubicibo** [comment]
Try to:
```
C:\...> cd .\SUPer
C:\...\SUPer> python3 -m pip install .
```

**Comment by KSSW** [comment]
Some errors have occurred: 
C:\Users\48716\Desktop\SUPer-main>python3 -m pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing c:\users\48716\desktop\super-main
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scenaristream@ git+https://github.com/cubicibo/ScenariStream.git (from SUPer==0.2.4)
  Cloning https://github.com/cubicibo/ScenariStream.git to c:\users\48716\appdata\local\temp\pip-install-z1hm7yv7\scenaristream_130409797c44422d90e1d1707897a5ab
  Running command git clone --filter=blob:none --quiet https://github.com/cubicibo/ScenariStream.git 'C:\Users\48716\AppData\Local\Temp\pip-install-z1hm7yv7\scenaristream_130409797c44422d90e1d1707897a5ab'
  Resolved https://github.com/cubicibo/ScenariStream.git to commit ed60a11a714728e6e55913b8e9a376ac2fc50288
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting piliq@ git+https://github.com/cubicibo/piliq.git (from SUPer==0.2.4)
  Cloning https://github.com/cubicibo/piliq.git to c:\users\48716\appdata\local\temp\pip-install-z1hm7yv7\piliq_00cd30ea5a79455cb1c19b9144dfeb64
  Running command git clone --filter=blob:none --quiet https://github.com/cubicibo/piliq.git 'C:\Users\48716\AppData\Local\Temp\pip-install-z1hm7yv7\piliq_00cd30ea5a79455cb1c19b9144dfeb64'
  Resolved https://github.com/cubicibo/piliq.git to commit 44aa8a1c4a0441d7205e2508538fca4b0522eec3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting brule@ git+https://github.com/cubicibo/brule.git (from SUPer==0.2.4)
  Cloning https://github.com/cubicibo/brule.git to c:\users\48716\appdata\local\temp\pip-install-z1hm7yv7\brule_91409e14067e491db05a01b376f8d819
  Running command git clone --filter=blob:none --quiet https://github.com/cubicibo/brule.git 'C:\Users\48716\AppData\Local\Temp\pip-install-z1hm7yv7\brule_91409e14067e491db05a01b376f8d819'
  Resolved https://github.com/cubicibo/brule.git to commit 65f04e03208a5dc28484e7766943b8e1a1dce069
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\48716\AppData\Local\Temp\pip-build-env-h56i61x2\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\48716\AppData\Local\Temp\pip-build-env-h56i61x2\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\48716\AppData\Local\Temp\pip-build-env-h56i61x2\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\48716\AppData\Local\Temp\pip-build-env-h56i61x2\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 79, in <module>
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

![image](https://github.com/cubicibo/ScenariStream/assets/76238373/b7fdfd97-a6a9-4013-94e9-34efd793e087)

**Comment by cubicibo** [comment]
Ah, this is a problem in "Brule". I have fixed it in https://github.com/cubicibo/brule/commit/f37f03f5a5fb6fe330c207f11c212bb045484a70, please try again.

**Comment by KSSW** [comment]
Thank you. I tried it successfully
![image](https://github.com/cubicibo/ScenariStream/assets/76238373/9832b89d-7e08-40d0-b080-02bc8bfae58a)
It seems like we can't fix it anymore

I can upload a SUP subtitle
[Drive Google](https://drive.google.com/file/d/1IeBo2Sy82Y2QJCxipmzZoRysN0P5sM61/view?usp=sharing)

**Comment by cubicibo** [comment]
- Everything from 00:00:00:01 to 00:08:24:01 is garbage.
- Everything after  01:37:47:10 up to the end is garbage.

There is nothing to salvage in these regions. Stream is critically corrupted and unusable. It will crash a Blu-ray Disc player.
What software did you use to generate these two sections? So I can rightfully throw a pie at the author face.

Stream analysis report:
[out.txt](https://github.com/user-attachments/files/15858155/out.txt)

**Comment by KSSW** [comment]
This sup was made by someone else
Belongs to the animation subtitle type

**Comment by cubicibo** [comment]
Then this person does not know how to generate SUPs. The stream is critically corrupted, animated subtitle or not.
